# Site settings
title: "Stadi Research & Analytics Ltd | Premier Research Consultancy in Kenya & East Africa"
email: "info@stadiresearch.com"
description: >-
  Leading research and analytics consultancy in Kenya & East Africa. Expert services in
  academic research support, market research, data analytics, monitoring & evaluation,
  and professional training (SPSS, R, Python, Stata). Serving students, universities,
  businesses, NGOs, and government agencies. 500+ projects | 98% satisfaction | 8+ years excellence.
baseurl: "/stadianalytics" # the subpath of your site, e.g. /blog
url: "https://atimamaranga.github.io" # your GitHub Pages URL
tagline: "Transform Data Into Strategic Insights"
keywords: "research consultancy Kenya, data analytics East Africa, thesis support, market research, SPSS training, statistical analysis, M&E services, research methods training"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  services:
    output: true
    permalink: /:collection/:name/
  portfolio:
    output: true
    permalink: /:collection/:name/
  team:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"

# SEO and Analytics
google_analytics: "" # Add your GA tracking ID
author: "Stadi Research & Analytics Ltd"

# Social media
social:
  twitter: ""
  linkedin: ""
  facebook: ""

# Company Information
company:
  name: "Stadi Research & Analytics Ltd"
  location: "Nairobi, Kenya"
  phone: "+254 XXX XXX XXX"
  email: "info@stadiresearch.com"
  address: "Nairobi, Kenya"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
