# Site settings
title: "Stadi Research & Analytics Ltd"
email: "info@stadiresearch.com"
description: >-
  Professional research and analytics consulting services in East Africa. 
  Academic support, corporate research, data analytics, and capacity building 
  for students, institutions, businesses, and organizations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stadiresearch.github.io" # your GitHub Pages URL

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  services:
    output: true
    permalink: /:collection/:name/
  portfolio:
    output: true
    permalink: /:collection/:name/
  team:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"

# SEO and Analytics
google_analytics: "" # Add your GA tracking ID
author: "Stadi Research & Analytics Ltd"

# Social media
social:
  twitter: ""
  linkedin: ""
  facebook: ""

# Company Information
company:
  name: "Stadi Research & Analytics Ltd"
  location: "Nairobi, Kenya"
  phone: "+254 XXX XXX XXX"
  email: "info@stadiresearch.com"
  address: "Nairobi, Kenya"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
